package com.pigx.engine.core.definition.constant;


public interface BaseConstants {

    /* ---------- 配置属性通用常量 ---------- */
    String PROPERTY_NAME_ENABLED = "enabled";
    String PROPERTY_ENABLED = SymbolConstants.PERIOD + PROPERTY_NAME_ENABLED;
    String PROPERTY_PREFIX_SERVER = "server";
    String PROPERTY_PREFIX_SPRING = "spring";
    String PROPERTY_PREFIX_HERODOTUS = "herodotus";
    String PROPERTY_PREFIX_REACTIVE = PROPERTY_PREFIX_HERODOTUS + ".reactive";
    String PROPERTY_REACTIVE_WEBCLIENT = PROPERTY_PREFIX_REACTIVE + ".web-client";
    String PROPERTY_SERVER_SERVLET = PROPERTY_PREFIX_SERVER + ".servlet";
    String ITEM_SERVLET_CONTEXT_PATH = PROPERTY_SERVER_SERVLET + ".context-path";
    String PROPERTY_SPRING_DATA = PROPERTY_PREFIX_SPRING + ".data";
    String PROPERTY_SPRING_MAIL = PROPERTY_PREFIX_SPRING + ".mail";
    String PLACEHOLDER_PREFIX = "${";
    String PLACEHOLDER_SUFFIX = "}";
    /* ---------- Herodotus 自定义配置属性 ---------- */
    String PROPERTY_PREFIX_ASSISTANT = PROPERTY_PREFIX_HERODOTUS + ".assistant";
    String PROPERTY_PREFIX_CACHE = PROPERTY_PREFIX_HERODOTUS + ".cache";
    String PROPERTY_PREFIX_CRYPTO = PROPERTY_PREFIX_HERODOTUS + ".crypto";
    String ITEM_CRYPTO_STRATEGY = PROPERTY_PREFIX_CRYPTO + ".strategy";
    String PROPERTY_PREFIX_DATA = PROPERTY_PREFIX_HERODOTUS + ".data";
    String PROPERTY_PREFIX_ENDPOINT = PROPERTY_PREFIX_HERODOTUS + ".endpoint";
    String PROPERTY_PREFIX_LOG = PROPERTY_PREFIX_HERODOTUS + ".log";
    String PROPERTY_LOG_LOGSTASH = PROPERTY_PREFIX_LOG + ".logstash";
    String PROPERTY_PREFIX_MESSAGE = PROPERTY_PREFIX_HERODOTUS + ".message";
    String PROPERTY_PREFIX_OAUTH2 = PROPERTY_PREFIX_HERODOTUS + ".oauth2";
    String PROPERTY_OAUTH2_AUTHENTICATION = PROPERTY_PREFIX_OAUTH2 + ".authentication";
    String PROPERTY_OAUTH2_AUTHORIZATION = PROPERTY_PREFIX_OAUTH2 + ".authorization";
    String ITEM_AUTHORIZATION_TOKEN_FORMAT = PROPERTY_OAUTH2_AUTHORIZATION + ".token-format";
    String PROPERTY_PREFIX_OSS = PROPERTY_PREFIX_HERODOTUS + ".oss";

    /* ---------- Spring 家族配置属性 ---------- */
    String PROPERTY_PREFIX_PLATFORM = PROPERTY_PREFIX_HERODOTUS + ".platform";
    String ITEM_PLATFORM_DATA_ACCESS_STRATEGY = PROPERTY_PREFIX_PLATFORM + ".data-access-strategy";
    String ITEM_PLATFORM_ARCHITECTURE = PROPERTY_PREFIX_PLATFORM + ".architecture";
    String PROPERTY_PREFIX_SECURE = PROPERTY_PREFIX_HERODOTUS + ".secure";
    String PROPERTY_PREFIX_SERVICE = PROPERTY_PREFIX_HERODOTUS + ".service";
    String ITEM_SPRING_APPLICATION_NAME = PROPERTY_PREFIX_SPRING + ".application.name";
    String ITEM_SPRING_SQL_INIT_PLATFORM = PROPERTY_PREFIX_SPRING + ".sql.init.platform";
    String ANNOTATION_SQL_INIT_PLATFORM = PLACEHOLDER_PREFIX + ITEM_SPRING_SQL_INIT_PLATFORM + PLACEHOLDER_SUFFIX;

    /* ---------- 通用缓存常量 ---------- */

    String CACHE_PREFIX = "cache:";
    String CACHE_SIMPLE_BASE_PREFIX = CACHE_PREFIX + "simple:";
    String CACHE_TOKEN_BASE_PREFIX = CACHE_PREFIX + "token:";

    String AREA_PREFIX = "data:";

}
