package com.pigx.engine.core.definition.constant;

/* loaded from: core-definition-3.5.7.0.jar:cn/herodotus/engine/core/definition/constant/SystemConstants.class */
public interface SystemConstants {
    public static final String NONE = "none";
    public static final String TENANT_ID = "public";
    public static final String TREE_ROOT_ID = "0";
    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
    public static final String DN_OU = "Herodotus Cloud";
    public static final String WEBSITE = "https://www.herodotus.vip";
    public static final String COPYRIGHT_DETAILS = "AGPL-3.0 Licensed | Copyright © 2020-2030 码 匠 君";
    public static final String SYSTEM_NAME = "Herodotus Cloud";
    public static final String PACKAGE_NAME = "com.pigx";
    public static final String OPEN_API_SECURITY_SCHEME_BEARER_NAME = "HERODOTUS_AUTH";
    public static final String BEARER_TYPE = "Bearer";
    public static final String BEARER_TOKEN = "Bearer ";
    public static final String BASIC_TYPE = "Basic";
    public static final String BASIC_TOKEN = "Basic ";
    public static final String OAUTH2_AUTHORIZATION_ENDPOINT = "/oauth2/authorize";
    public static final String OAUTH2_PUSHED_AUTHORIZATION_REQUEST_ENDPOINT = "/oauth2/par";
    public static final String OAUTH2_TOKEN_ENDPOINT = "/oauth2/token";
    public static final String OAUTH2_TOKEN_REVOCATION_ENDPOINT = "/oauth2/revoke";
    public static final String OAUTH2_TOKEN_INTROSPECTION_ENDPOINT = "/oauth2/introspect";
    public static final String OAUTH2_DEVICE_AUTHORIZATION_ENDPOINT = "/oauth2/device_authorization";
    public static final String OAUTH2_DEVICE_VERIFICATION_ENDPOINT = "/oauth2/device_verification";
    public static final String OAUTH2_JWK_SET_ENDPOINT = "/oauth2/jwks";
    public static final String OIDC_CLIENT_REGISTRATION_ENDPOINT = "/connect/register";
    public static final String OIDC_LOGOUT_ENDPOINT = "/connect/logout";
    public static final String OIDC_USER_INFO_ENDPOINT = "/userinfo";
    public static final String OAUTH2_AUTHORIZATION_CONSENT_URI = "/oauth2/consent";
    public static final String OAUTH2_DEVICE_ACTIVATION_URI = "/oauth2/device_activation";
    public static final String OAUTH2_DEVICE_VERIFICATION_SUCCESS_URI = "/device_activated";
    public static final String OAUTH2_DEVICE_VERIFICATION_FAILURE_URI = "/device_activation_failure";
    public static final String KEY__USER_PRINCIPAL = "USER_PRINCIPAL";
    public static final String PASSWORD = "password";
    public static final String SOCIAL_CREDENTIALS = "social_credentials";
    public static final String CODE = "code";
    public static final String USERNAME = "username";
    public static final String ROLES = "roles";
    public static final String AUTHORITIES = "authorities";
    public static final String EMPLOYEE_ID = "employeeId";
    public static final String AVATAR = "avatar";
    public static final String PRINCIPAL = "principal";
    public static final String SOURCE = "source";
    public static final String LICENSE = "license";
    public static final String COPYRIGHT = "copyright";
    public static final String SCOPE_OPENID = "openid";
    public static final String SCOPE_EMAIL = "email";
    public static final String SCOPE_PROFILE = "profile";
    public static final String SCOPE_ADDRESS = "address";
    public static final String SCOPE_PHONE = "phone";
    public static final String SCOPE_CLIENT_CREATE = "client.create";
    public static final String SCOPE_CLIENT_READ = "client.read";
}
